---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-app-nginx
  name: hello-app-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app-nginx
  template:
    metadata:
      labels:
        app: hello-app-nginx
    spec:
      containers:
      - image: nginx:1.17-alpine
        name: hello-app-nginx
        ports:
        - containerPort: 80
          name: hello-app-nginx
