apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: winebarrel
  region: ap-northeast-1

nodeGroups:
  - name: winebarrel-ng-workers
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 15
    privateNetworking: true
    tags:
      datadog: "true"
    # cf. https://eksctl.io/usage/iam-policies/
    iam:
      instanceRoleARN: arn:aws:iam::822997939312:role/nodegroup-winebarrel-ng-workers
      instanceProfileARN: arn:aws:iam::822997939312:instance-profile/nodegroup-winebarrel-ng-workers
