version: '3.7'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      LOG_TO_STDOUT: 1
      RAILS_ENV: development
      DATABASE_URL: mysql2://root@db:3306/hello-app_development
    depends_on:
      - db
