version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - kubernetes/install
      - run:
          command: >
            echo hello
orbs:
  kubernetes: circleci/kubernetes@0.3.0
